# Generated by Django 6.0.4 on 2026-04-27 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='широта')),
                ('longitude', models.FloatField(verbose_name='долгота')),
                ('height', models.IntegerField(verbose_name='высота')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(blank=True, max_length=50, null=True, verbose_name='уровень сложности зимой')),
                ('spring', models.CharField(blank=True, max_length=50, null=True, verbose_name='уровень сложности весной')),
                ('summer', models.CharField(blank=True, max_length=50, null=True, verbose_name='уровень сложности летом')),
                ('autumn', models.CharField(blank=True, max_length=50, null=True, verbose_name='уровень сложности осенью')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('fam', models.CharField(max_length=50, verbose_name='фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('otc', models.CharField(blank=True, max_length=50, null=True, verbose_name='отчество')),
                ('phone', models.CharField(max_length=50, verbose_name='мобильный телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='красивое название')),
                ('title', models.CharField(max_length=250, verbose_name='основное название')),
                ('other_titles', models.CharField(blank=True, max_length=250, null=True, verbose_name='другие названия')),
                ('connect', models.CharField(blank=True, max_length=250, null=True, verbose_name='информация о соединениях')),
                ('add_time', models.DateTimeField(verbose_name='время добавления')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('pending', 'Ожидает'), ('accepted', 'Принят'), ('rejected', 'Отклонён')], default='new', max_length=10, verbose_name='статус модерации')),
                ('coords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passes_api.coords')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passes_api.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passes_api.users')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(verbose_name='данные изображения')),
                ('title', models.CharField(max_length=50, verbose_name='название изображения')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='passes_api.pereval')),
            ],
        ),
    ]
