# Generated by Django 6.0.4 on 2026-04-24 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes_api', '0002_alter_pereval_connect_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='pereval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='passes_api.pereval'),
        ),
    ]
