# Generated by Django 6.0.4 on 2026-04-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes_api', '0003_alter_images_pereval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='connect',
            field=models.CharField(max_length=250, verbose_name='информация о соединениях'),
        ),
    ]
