# Generated by Django 6.0.4 on 2026-04-26 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passes_api', '0004_alter_pereval_connect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pereval',
            old_name='coord',
            new_name='coords',
        ),
    ]
