# Generated by Django 6.0.4 on 2026-04-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes_api', '0005_rename_coord_pereval_coords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='add_time',
            field=models.DateTimeField(verbose_name='время добавления'),
        ),
    ]
